using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using IKVM.Attributes;

[assembly: InternalsVisibleTo("javaparser-ikvm-runtime-injected, PublicKey=00240000048000009400000006020000002400005253413100040000010001009D674F3D63B8D7A4C428BD7388341B025C71AA61C6224CD53A12C21330A3159D300051FE2EED154FE30D70673A079E4529D0FD78113DCA771DA8B0C1EF2F77B73651D55645B0A4294F0AF9BF7078432E13D0F46F951D712C2FCF02EB15552C0FE7817FC0AED58E0984F86661BF64D882F29B619899DD264041E7D4992548EB9E")]
[assembly: AssemblyVersion("0.0.0.0")]
[module: SourceFile(null)]
[module: JavaModule(Jars = new string[] { "javaparser.jar" })]
[module: PackageList("javaparser.jar", new string[]
{
	"com.github.javaparser.generator.core", "com.github.javaparser.generator", "com.github.javaparser.generator.core.node", "com.github.javaparser.generator.core.other", "com.github.javaparser.generator.core.utils", "com.github.javaparser.generator.core.visitor", "com.github.javaparser", "com.github.javaparser.ast", "com.github.javaparser.ast.observer", "com.github.javaparser.ast.visitor",
	"com.github.javaparser.ast.nodeTypes", "com.github.javaparser.ast.body", "com.github.javaparser.ast.nodeTypes.modifiers", "com.github.javaparser.resolution", "com.github.javaparser.ast.comments", "com.github.javaparser.ast.expr", "com.github.javaparser.printer", "com.github.javaparser.ast.modules", "com.github.javaparser.ast.stmt", "com.github.javaparser.ast.type",
	"com.github.javaparser.ast.validator", "com.github.javaparser.ast.validator.language_level_validations.chunks", "com.github.javaparser.ast.validator.language_level_validations", "com.github.javaparser.ast.validator.postprocessors", "com.github.javaparser.javadoc.description", "com.github.javaparser.javadoc", "com.github.javaparser.metamodel", "com.github.javaparser.printer.concretesyntaxmodel", "com.github.javaparser.printer.configuration", "com.github.javaparser.printer.lexicalpreservation",
	"com.github.javaparser.printer.lexicalpreservation.changes", "com.github.javaparser.resolution.declarations", "com.github.javaparser.resolution.types.parametrization", "com.github.javaparser.resolution.types", "com.github.javaparser.utils", "com.github.javaparser.generator.metamodel", "com.github.javaparser.serialization", "com.github.javaparser.symbolsolver.cache", "com.github.javaparser.symbolsolver.core.resolution", "com.github.javaparser.symbolsolver.declarations.common",
	"com.github.javaparser.symbolsolver.javaparser", "com.github.javaparser.symbolsolver.javaparsermodel.contexts", "com.github.javaparser.symbolsolver.javaparsermodel.declarations", "com.github.javaparser.symbolsolver.logic", "com.github.javaparser.symbolsolver.resolution", "com.github.javaparser.symbolsolver.javaparsermodel.declarators", "com.github.javaparser.symbolsolver.javaparsermodel", "com.github.javaparser.symbolsolver.javassistmodel", "com.github.javaparser.symbolsolver", "com.github.javaparser.symbolsolver.model.resolution",
	"com.github.javaparser.symbolsolver.model.typesystem", "com.github.javaparser.symbolsolver.reflectionmodel.comparators", "com.github.javaparser.symbolsolver.reflectionmodel", "com.github.javaparser.symbolsolver.resolution.naming", "com.github.javaparser.symbolsolver.resolution.promotion", "com.github.javaparser.symbolsolver.resolution.typeinference", "com.github.javaparser.symbolsolver.resolution.typeinference.bounds", "com.github.javaparser.symbolsolver.resolution.typeinference.constraintformulas", "com.github.javaparser.symbolsolver.resolution.typesolvers", "com.github.javaparser.symbolsolver.utils",
	"com.google.common.util.concurrent.internal", "com.google.common.annotations", "com.google.common.base", "com.google.common.base.internal", "com.google.common.cache", "com.google.common.collect", "com.google.common.escape", "com.google.common.eventbus", "com.google.common.graph", "com.google.common.hash",
	"com.google.common.html", "com.google.common.io", "com.google.common.math", "com.google.common.net", "com.google.common.primitives", "com.google.common.reflect", "com.google.common.util.concurrent", "com.google.common.xml", "com.google.thirdparty.publicsuffix", "javassist",
	"javassist.bytecode", "javassist.bytecode.analysis", "javassist.bytecode.stackmap", "javassist.bytecode.annotation", "javassist.compiler", "javassist.compiler.ast", "javassist.convert", "javassist.expr", "javassist.runtime", "javassist.scopedpool",
	"javassist.tools", "javassist.tools.reflect", "javassist.tools.web", "javassist.tools.rmi", "javassist.util", "javassist.util.proxy", "javax.json", "javax.json.spi", "javax.json.stream", "com.google.errorprone.annotations",
	"com.google.errorprone.annotations.concurrent", "com.google.j2objc.annotations", "org.checkerframework.checker.builder.qual", "org.checkerframework.checker.calledmethods.qual", "org.checkerframework.checker.compilermsgs.qual", "org.checkerframework.checker.fenum.qual", "org.checkerframework.checker.formatter.qual", "org.checkerframework.checker.guieffect.qual", "org.checkerframework.checker.i18n.qual", "org.checkerframework.checker.i18nformatter.qual",
	"org.checkerframework.checker.index.qual", "org.checkerframework.checker.initialization.qual", "org.checkerframework.checker.interning.qual", "org.checkerframework.checker.lock.qual", "org.checkerframework.checker.nullness.qual", "org.checkerframework.checker.optional.qual", "org.checkerframework.checker.propkey.qual", "org.checkerframework.checker.regex.qual", "org.checkerframework.checker.signature.qual", "org.checkerframework.checker.signedness.qual",
	"org.checkerframework.checker.tainting.qual", "org.checkerframework.checker.units.qual", "org.checkerframework.common.aliasing.qual", "org.checkerframework.common.initializedfields.qual", "org.checkerframework.common.reflection.qual", "org.checkerframework.common.returnsreceiver.qual", "org.checkerframework.common.subtyping.qual", "org.checkerframework.common.util.report.qual", "org.checkerframework.common.value.qual", "org.checkerframework.dataflow.qual",
	"org.checkerframework.framework.qual", "javax.annotation", "javax.annotation.concurrent", "javax.annotation.meta"
})]
